### ISSUE TITLE
More signs

### ISSUE THREAD

**Issue by tordans** [osmberlin/osm-traffic-sign-tool#30]
https://de.wikipedia.org/wiki/Bildtafel_der_Verkehrszeichen_in_der_Bundesrepublik_Deutschland_seit_2017#Zusatzzeichen

```[tasklist]
### Tasks
- [x] Zusatzzeichen 1012-31 Ende https://de.wikipedia.org/wiki/Datei:Zusatzzeichen_1012-31_-_Ende_(600x330),_StVO_1992.svg
- [x] Zusatzzeichen 1000-30 Beide Richtungen, zwei gegengerichtete waagerechte Pfeile https://de.wikipedia.org/wiki/Datei:Zusatzzeichen_1000-30_-_beide_Richtungen,_zwei_gegengerichtete_waagerechte_Pfeile,_StVO_1992.svg
- [x] 1000-31 Beide Richtungen, zwei gegengerichtete senkrechte Pfeile https://de.wikipedia.org/wiki/Datei:Zusatzzeichen_1000-31_-_beide_Richtungen,_zwei_gegengerichtete_senkrechte_Pfeile,_StVO_1992.svg
```
